version: '3.3'
services:
    cache-proxy-service:
        image: nginx
        container_name: cache-proxy-service
        ports:
            - '80:80'
        volumes:
            - './overlays/cache-proxy-service/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
    cache-dns-01:
        image: 'steamcache/steamcache-dns:latest'
        container_name: cache-dns-01
        environment:
            - STEAMCACHE_IP=192.168.1.34
        depends_on:
            - cache-proxy-service
        ports:
            - '53:53/udp'
    ser_9b78c0c36b729473df5d3099dfefd6cf:
        image: 'steamcache/monolithic:latest'
        container_name: cache-steam-380600
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
        volumes:
            - 'vol_9b78c0c36b729473df5d3099dfefd6cf:/data'
        depends_on:
            - cache-proxy-service
        restart: unless-stopped
        expose:
            - '80'
volumes:
    vol_9b78c0c36b729473df5d3099dfefd6cf: {  }
